---
train:

    params:
        batch_size: 128
        epoch: 80
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "gaze_estimation/save_model/transformer/Transformer-6layers"
        folder: mpii
        model_name: trans6
        step: 10

    data:
        image: "datasets/FaceBased/MPIIFaceGaze/Image"
        label: "datasets/FaceBased/MPIIFaceGaze/Label"
        header: True
        name: mpii
        isFolder: True
        
    pretrain:
        enable: True
        path: "models/GazeTR-H-ETH.pt"
        device: 0

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
