---
train:

    params:
        batch_size: 128
        epoch: 15
        lr: 0.0005
        decay: 0.5
        decay_step: 10
        warmup: 3
        

    save:
        metapath: "transform/eth_res50_vali_yaw_pitch"
        folder: eth
        model_name: trans6
        step: 1

    data:
        image: "/datasets/xgaze/Image"
        label: "/datasets/xgaze/Label"
        header: True
        name: eth
        isFolder: True
        w_p: True

    pretrain:
        enable: False
        path: "transform/eth_res50_vali_yaw_pitch/eth/checkpoint/Iter_30_trans6.pt"
        device: 0

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
